workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build archive
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app
