workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS app (no codesign)
        script: flutter build ios --release --no-codesign

      - name: Create IPA from .app
        script: |
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - Runner.ipa
